name: CI Pipeline

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubunt-latest
    steps:
      - name: Checkout code 
        uses:actions/Checkout@v3

      - name: Setup Node.jobs
        uses: actions/setup-node@v3

      - name: Install Dependencies
        run: npm install 


      - name: Run Tests
        run:npm test
